test:
	./divisor_sample < test1.in > expected1.out
	./divisor_sample < test2.in > expected2.out
	./divisor_sample < test3.in > expected3.out
	./divisor_sample < test4.in > expected4.out
	./divisors < test1.in > actual1.out
	./divisors < test2.in > actual2.out
	./divisors < test3.in > actual3.out
	./divisors < test4.in > actual4.out
	diff actual1.out expected1.out
	diff actual2.out expected2.out
	diff actual3.out expected3.out
	diff actual4.out expected4.out






